### ISSUE TITLE
Unable to run this mod on a server

### ISSUE THREAD

**Issue by losslauralin** [impleri/player-skills#14]
Game version: 1.19.2 fabric
Mod version: 1.2.0
Environment: Just PlayerSkills and KubeJS In fabric-server-mc.1.19.2-loader.0.14.11
Description: It happend in Server start and stop
Crash report:[crash-2022-12-21_19.31.31-server.txt](https://github.com/impleri/player-skills/files/10277408/crash-2022-12-21_19.31.31-server.txt)

**Comment by 948872003** [comment]
It also happend in server stoping ,in net.impleri.playerskills.server.PlayerSkillsServer.beforeSeverStops

**Comment by impleri** [comment]
I've finally set up a server locally for testing. There's a few other kinks to work out with item-skills, but I should have 1.2.1 with a functional server-side in the next day or so.

**Comment by impleri** [comment]
We think this is fixed in v1.2.1.
