### ISSUE TITLE
Player Skills crash with KubeJS

### ISSUE THREAD

**Issue by Kzeroko** [impleri/player-skills#21]
https://pastebin.com/mHF4Dt08
Here's the crash report

The latest working version for me is player-skills-1.2.1-fabric

**Comment by impleri** [comment]
Thanks. I can reproduce the error. Interestingly, that error message only shows up on the server. Client-side just closes silently without any error in the logs.
It's working fine on Forge (both client/solo and server).  And the changes from [1.2.1 to 1.2.2](https://github.com/impleri/player-skills/compare/1.2.1...1.2.2) are pretty minimal. I have a thought for the fix (migrating the Skills and SkillType registry wrappers to non-static methods).
