### ISSUE TITLE
preventing from creating world

### ISSUE THREAD

**Issue by mrdrip404** [impleri/player-skills#32]
I don't know why but this mod prevents me from creating a brand new world. no crash reports or logs

**Comment by mrdrip404** [comment]
update, now log recorded

**Comment by mrdrip404** [comment]
[2023-03-03-3.log.gz](https://github.com/impleri/player-skills/files/10886194/2023-03-03-3.log.gz)

**Comment by impleri** [comment]
Looking at the logs, it looks like none of the xSkills mods are even loaded.

**Comment by impleri** [comment]
Closing as stale
