### ISSUE TITLE
[Feature request] Multiple skills restrictions

### ISSUE THREAD

**Issue by Cyo90** [impleri/player-skills#67]
I'm not sure if this is the correct place to ask this, sorry if it's not.

First of all, **thank you so much** for this mod. Im having a lot of fun, and the possibilities are insane when creating quests and unlocking restrictions. I'm just missing a feature that I think it would be great to add in the future to further expand the customizations.

The **feature** would be the possibility to **require just one of multiple skills to unlock a restrictions**. For example restrict the use of Golden Apples unless you acquired the skill 'A' --**OR**-- the skill 'B'. Requiring two or more skills to unlock something would be great too (skills 'A' --**AND**-- skill 'B' to unlock restriction 'X').

I'm not 100% sure if this feature is already present in some form but I dind't see anything on the readme. Sorry if it's the case.

And thank you again for your work, keep it going! :)

**Comment by impleri** [comment]
So the condition building for restrictions allows this already:
`restrict.if(player => player.cannot(skillA) && player.cannot(skillB))` If the player has A or B, the restriction won't apply
